services:
  central_banks_scrapper:
    container_name: central_banks_scrapper_container
    image: central_banks_scrapper:latest
    env_file: .env

    volumes:
    - ${HOME}/agticreds:/app/agticreds:ro

    restart: always
    logging:
      options:
        max-size: 100m