services:
  db:
    container_name: test_db
    image: postgres:16.3
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test_db
    ports:
      - '5555:5555'
    command: postgres -c port=5555
    volumes:
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql