services:
  db:
    container_name: test_db
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test_db
    ports:
      - '5555:5432'
    volumes:
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql